force-app/main/default/objects/WebService__mdt/WebService__mdt.object-meta.xml
<CustomObject>
    <label>Web Service</label>
    <pluralLabel>Web Services</pluralLabel>
</CustomObject>

force-app/main/default/objects/WebService__mdt/fields/API_KEY__c.field-meta.xml
<CustomField>
    <fullName>API_KEY__c</fullName>
    <label>API KEY</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/Cls_CJ_SFtoSFMC.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 05-14-2025
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class Cls_CJ_SFtoSFMC {
	
	public static HttpResponse sendRequest(String setting, String body){

		WebService__mdt serviceMetadata = WebService__mdt.getInstance(setting);

		try {

			HttpRequest req = new HttpRequest();
			req.setEndpoint(serviceMetadata.Endpoint__c);
			req.setMethod('POST');
			req.setHeader('Content-Type', 'application/json');
			req.setHeader('api-key', serviceMetadata.API_KEY__c);
			req.setBody(body);

			Http http = new Http();
			HttpResponse res = http.send(req);

			System.debug('Brevo Response: ' + res.getBody());
			return res;

		} catch (Exception exc) {
			System.debug( ' Exception Message: ' + exc.getMessage() );
			System.debug( ' Stack Trace: ' + exc.getStackTraceString() );
			throw exc;
		}


	}
}